server:
  port: 80

spring:
  datasource:
    druid:
      username: root
      password: Jpkc123456
      url: jdbc:mysql://47.108.151.199:3306/shiro
      initial-size: 1
      min-idle: 1
      max-active: 20
    driver-class-name: com.mysql.cj.jdbc.Driver

  #redis
  redis:
    host: 47.108.151.199
    port: 6379

mybatis:
  configuration:
    use-actual-param-name: on